---

- name: Add RabbitMQ vhosts
  rabbitmq_vhost:
    name: '{{ item.name }}'
    node: '{{ item.node | default("rabbit") }}'
    state: present
    tracing: '{{ item.tracing | default("no") }}'
  with_items: '{{ rabbitmq_vhosts }}'

- name: Add RabbitMQ users and set privileges
  rabbitmq_user:
    user: '{{ item.user }}'
    password: '{{ item.password }}'
    vhost: '{{ item.vhost | default("/") }}'
    node: '{{ item.node | default("rabbit") }}'
    tags: '{{ (item.tags | default("")) | join(",") }}'
    configure_priv: '{{ item.configure_priv | default(".*") }}'
    read_priv: '{{ item.read_priv | default(".*") }}'
    write_priv: '{{ item.write_priv | default(".*") }}'
    state: present
    force: '{{ item.force|default("no") }}'
  with_items: '{{ rabbitmq_users }}'
